with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "{{.InterfaceName}}.go"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
mockname: "{{.InterfaceName}}"      # ← tanpa prefix Mock
packages:
  starter-wahcah-be/internal/modules:
    config:
      recursive: true
      all: true