// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "starter-wahcah-be/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: user
func (_m *Repository) Create(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *models.User
func (_e *Repository_Expecter) Create(user interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *Repository_Create_Call) Run(run func(user *models.User)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 error) *Repository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(*models.User) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserRole provides a mock function with given fields: userRole
func (_m *Repository) CreateUserRole(userRole *models.UserRole) error {
	ret := _m.Called(userRole)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.UserRole) error); ok {
		r0 = rf(userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserRole'
type Repository_CreateUserRole_Call struct {
	*mock.Call
}

// CreateUserRole is a helper method to define mock.On call
//   - userRole *models.UserRole
func (_e *Repository_Expecter) CreateUserRole(userRole interface{}) *Repository_CreateUserRole_Call {
	return &Repository_CreateUserRole_Call{Call: _e.mock.On("CreateUserRole", userRole)}
}

func (_c *Repository_CreateUserRole_Call) Run(run func(userRole *models.UserRole)) *Repository_CreateUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.UserRole))
	})
	return _c
}

func (_c *Repository_CreateUserRole_Call) Return(_a0 error) *Repository_CreateUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateUserRole_Call) RunAndReturn(run func(*models.UserRole) error) *Repository_CreateUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: email
func (_m *Repository) FindByEmail(email string) (*models.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type Repository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *Repository_Expecter) FindByEmail(email interface{}) *Repository_FindByEmail_Call {
	return &Repository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *Repository_FindByEmail_Call) Run(run func(email string)) *Repository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindByEmail_Call) Return(_a0 *models.User, _a1 error) *Repository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByEmail_Call) RunAndReturn(run func(string) (*models.User, error)) *Repository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindDefaultRole provides a mock function with no fields
func (_m *Repository) FindDefaultRole() (*models.Role, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindDefaultRole")
	}

	var r0 *models.Role
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.Role, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.Role); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindDefaultRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDefaultRole'
type Repository_FindDefaultRole_Call struct {
	*mock.Call
}

// FindDefaultRole is a helper method to define mock.On call
func (_e *Repository_Expecter) FindDefaultRole() *Repository_FindDefaultRole_Call {
	return &Repository_FindDefaultRole_Call{Call: _e.mock.On("FindDefaultRole")}
}

func (_c *Repository_FindDefaultRole_Call) Run(run func()) *Repository_FindDefaultRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_FindDefaultRole_Call) Return(_a0 *models.Role, _a1 error) *Repository_FindDefaultRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindDefaultRole_Call) RunAndReturn(run func() (*models.Role, error)) *Repository_FindDefaultRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
