// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	register "starter-wahcah-be/internal/modules/auth/register"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: req
func (_m *Service) Register(req register.RegisterRequest) (*register.RegisterResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *register.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(register.RegisterRequest) (*register.RegisterResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(register.RegisterRequest) *register.RegisterResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*register.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(register.RegisterRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Service_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - req register.RegisterRequest
func (_e *Service_Expecter) Register(req interface{}) *Service_Register_Call {
	return &Service_Register_Call{Call: _e.mock.On("Register", req)}
}

func (_c *Service_Register_Call) Run(run func(req register.RegisterRequest)) *Service_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(register.RegisterRequest))
	})
	return _c
}

func (_c *Service_Register_Call) Return(_a0 *register.RegisterResponse, _a1 error) *Service_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Register_Call) RunAndReturn(run func(register.RegisterRequest) (*register.RegisterResponse, error)) *Service_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
