// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	login "starter-wahcah-be/internal/modules/auth/login"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: req
func (_m *Service) Authenticate(req login.LoginRequest) (*login.LoginResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *login.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(login.LoginRequest) (*login.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(login.LoginRequest) *login.LoginResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*login.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(login.LoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type Service_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - req login.LoginRequest
func (_e *Service_Expecter) Authenticate(req interface{}) *Service_Authenticate_Call {
	return &Service_Authenticate_Call{Call: _e.mock.On("Authenticate", req)}
}

func (_c *Service_Authenticate_Call) Run(run func(req login.LoginRequest)) *Service_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(login.LoginRequest))
	})
	return _c
}

func (_c *Service_Authenticate_Call) Return(_a0 *login.LoginResponse, _a1 error) *Service_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Authenticate_Call) RunAndReturn(run func(login.LoginRequest) (*login.LoginResponse, error)) *Service_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
