// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	login "starter-wahcah-be/internal/modules/auth/login"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: req
func (_m *Service) Authenticate(req login.LoginRequest) (*login.LoginResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *login.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(login.LoginRequest) (*login.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(login.LoginRequest) *login.LoginResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*login.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(login.LoginRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
