// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "starter-wahcah-be/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: userRole
func (_m *Repository) Create(userRole *models.UserRole) error {
	ret := _m.Called(userRole)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.UserRole) error); ok {
		r0 = rf(userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userRole *models.UserRole
func (_e *Repository_Expecter) Create(userRole interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", userRole)}
}

func (_c *Repository_Create_Call) Run(run func(userRole *models.UserRole)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.UserRole))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 error) *Repository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(*models.UserRole) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *Repository_Expecter) Delete(id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *Repository_Delete_Call) Run(run func(id uint)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(uint) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: page, limit, userID
func (_m *Repository) FindAll(page int, limit int, userID *uint) ([]models.UserRole, int64, error) {
	ret := _m.Called(page, limit, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.UserRole
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, *uint) ([]models.UserRole, int64, error)); ok {
		return rf(page, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(int, int, *uint) []models.UserRole); ok {
		r0 = rf(page, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, *uint) int64); ok {
		r1 = rf(page, limit, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, *uint) error); ok {
		r2 = rf(page, limit, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - page int
//   - limit int
//   - userID *uint
func (_e *Repository_Expecter) FindAll(page interface{}, limit interface{}, userID interface{}) *Repository_FindAll_Call {
	return &Repository_FindAll_Call{Call: _e.mock.On("FindAll", page, limit, userID)}
}

func (_c *Repository_FindAll_Call) Run(run func(page int, limit int, userID *uint)) *Repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(*uint))
	})
	return _c
}

func (_c *Repository_FindAll_Call) Return(_a0 []models.UserRole, _a1 int64, _a2 error) *Repository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindAll_Call) RunAndReturn(run func(int, int, *uint) ([]models.UserRole, int64, error)) *Repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id uint) (*models.UserRole, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.UserRole
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.UserRole, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.UserRole); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *Repository_Expecter) FindByID(id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *Repository_FindByID_Call) Run(run func(id uint)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *models.UserRole, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(uint) (*models.UserRole, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndRoleID provides a mock function with given fields: userID, roleID
func (_m *Repository) FindByUserIDAndRoleID(userID uint, roleID uint) (*models.UserRole, error) {
	ret := _m.Called(userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndRoleID")
	}

	var r0 *models.UserRole
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (*models.UserRole, error)); ok {
		return rf(userID, roleID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) *models.UserRole); ok {
		r0 = rf(userID, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(userID, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByUserIDAndRoleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndRoleID'
type Repository_FindByUserIDAndRoleID_Call struct {
	*mock.Call
}

// FindByUserIDAndRoleID is a helper method to define mock.On call
//   - userID uint
//   - roleID uint
func (_e *Repository_Expecter) FindByUserIDAndRoleID(userID interface{}, roleID interface{}) *Repository_FindByUserIDAndRoleID_Call {
	return &Repository_FindByUserIDAndRoleID_Call{Call: _e.mock.On("FindByUserIDAndRoleID", userID, roleID)}
}

func (_c *Repository_FindByUserIDAndRoleID_Call) Run(run func(userID uint, roleID uint)) *Repository_FindByUserIDAndRoleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *Repository_FindByUserIDAndRoleID_Call) Return(_a0 *models.UserRole, _a1 error) *Repository_FindByUserIDAndRoleID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByUserIDAndRoleID_Call) RunAndReturn(run func(uint, uint) (*models.UserRole, error)) *Repository_FindByUserIDAndRoleID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
