// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	crud_user_role "starter-wahcah-be/internal/modules/user_role/crud_user_role"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: req
func (_m *Service) Create(req crud_user_role.CreateUserRoleRequest) (*crud_user_role.UserRoleSingleResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *crud_user_role.UserRoleSingleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(crud_user_role.CreateUserRoleRequest) (*crud_user_role.UserRoleSingleResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(crud_user_role.CreateUserRoleRequest) *crud_user_role.UserRoleSingleResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crud_user_role.UserRoleSingleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(crud_user_role.CreateUserRoleRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Service_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - req crud_user_role.CreateUserRoleRequest
func (_e *Service_Expecter) Create(req interface{}) *Service_Create_Call {
	return &Service_Create_Call{Call: _e.mock.On("Create", req)}
}

func (_c *Service_Create_Call) Run(run func(req crud_user_role.CreateUserRoleRequest)) *Service_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(crud_user_role.CreateUserRoleRequest))
	})
	return _c
}

func (_c *Service_Create_Call) Return(_a0 *crud_user_role.UserRoleSingleResponse, _a1 error) *Service_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Create_Call) RunAndReturn(run func(crud_user_role.CreateUserRoleRequest) (*crud_user_role.UserRoleSingleResponse, error)) *Service_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Service_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *Service_Expecter) Delete(id interface{}) *Service_Delete_Call {
	return &Service_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *Service_Delete_Call) Run(run func(id uint)) *Service_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Service_Delete_Call) Return(_a0 error) *Service_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Delete_Call) RunAndReturn(run func(uint) error) *Service_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: page, limit, userID
func (_m *Service) GetAll(page int, limit int, userID *uint) (*crud_user_role.UserRoleListResponse, error) {
	ret := _m.Called(page, limit, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *crud_user_role.UserRoleListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, *uint) (*crud_user_role.UserRoleListResponse, error)); ok {
		return rf(page, limit, userID)
	}
	if rf, ok := ret.Get(0).(func(int, int, *uint) *crud_user_role.UserRoleListResponse); ok {
		r0 = rf(page, limit, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crud_user_role.UserRoleListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, *uint) error); ok {
		r1 = rf(page, limit, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type Service_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - page int
//   - limit int
//   - userID *uint
func (_e *Service_Expecter) GetAll(page interface{}, limit interface{}, userID interface{}) *Service_GetAll_Call {
	return &Service_GetAll_Call{Call: _e.mock.On("GetAll", page, limit, userID)}
}

func (_c *Service_GetAll_Call) Run(run func(page int, limit int, userID *uint)) *Service_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(*uint))
	})
	return _c
}

func (_c *Service_GetAll_Call) Return(_a0 *crud_user_role.UserRoleListResponse, _a1 error) *Service_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetAll_Call) RunAndReturn(run func(int, int, *uint) (*crud_user_role.UserRoleListResponse, error)) *Service_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *Service) GetByID(id uint) (*crud_user_role.UserRoleSingleResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *crud_user_role.UserRoleSingleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*crud_user_role.UserRoleSingleResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *crud_user_role.UserRoleSingleResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crud_user_role.UserRoleSingleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Service_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint
func (_e *Service_Expecter) GetByID(id interface{}) *Service_GetByID_Call {
	return &Service_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *Service_GetByID_Call) Run(run func(id uint)) *Service_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Service_GetByID_Call) Return(_a0 *crud_user_role.UserRoleSingleResponse, _a1 error) *Service_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetByID_Call) RunAndReturn(run func(uint) (*crud_user_role.UserRoleSingleResponse, error)) *Service_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
