// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	models "starter-wahcah-be/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: permission
func (_m *Repository) Create(permission *models.Permission) error {
	ret := _m.Called(permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Permission) error); ok {
		r0 = rf(permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - permission *models.Permission
func (_e *Repository_Expecter) Create(permission interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", permission)}
}

func (_c *Repository_Create_Call) Run(run func(permission *models.Permission)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Permission))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 error) *Repository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(*models.Permission) error) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *Repository_Expecter) Delete(id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *Repository_Delete_Call) Run(run func(id uint)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(uint) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: page, limit, roleID
func (_m *Repository) FindAll(page int, limit int, roleID *uint) ([]models.Permission, int64, error) {
	ret := _m.Called(page, limit, roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Permission
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, *uint) ([]models.Permission, int64, error)); ok {
		return rf(page, limit, roleID)
	}
	if rf, ok := ret.Get(0).(func(int, int, *uint) []models.Permission); ok {
		r0 = rf(page, limit, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, *uint) int64); ok {
		r1 = rf(page, limit, roleID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, *uint) error); ok {
		r2 = rf(page, limit, roleID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - page int
//   - limit int
//   - roleID *uint
func (_e *Repository_Expecter) FindAll(page interface{}, limit interface{}, roleID interface{}) *Repository_FindAll_Call {
	return &Repository_FindAll_Call{Call: _e.mock.On("FindAll", page, limit, roleID)}
}

func (_c *Repository_FindAll_Call) Run(run func(page int, limit int, roleID *uint)) *Repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(*uint))
	})
	return _c
}

func (_c *Repository_FindAll_Call) Return(_a0 []models.Permission, _a1 int64, _a2 error) *Repository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindAll_Call) RunAndReturn(run func(int, int, *uint) ([]models.Permission, int64, error)) *Repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *Repository) FindByID(id uint) (*models.Permission, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Permission, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Permission); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *Repository_Expecter) FindByID(id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *Repository_FindByID_Call) Run(run func(id uint)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *models.Permission, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(uint) (*models.Permission, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoleIDAndName provides a mock function with given fields: roleID, name
func (_m *Repository) FindByRoleIDAndName(roleID uint, name string) (*models.Permission, error) {
	ret := _m.Called(roleID, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoleIDAndName")
	}

	var r0 *models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (*models.Permission, error)); ok {
		return rf(roleID, name)
	}
	if rf, ok := ret.Get(0).(func(uint, string) *models.Permission); ok {
		r0 = rf(roleID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(roleID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByRoleIDAndName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoleIDAndName'
type Repository_FindByRoleIDAndName_Call struct {
	*mock.Call
}

// FindByRoleIDAndName is a helper method to define mock.On call
//   - roleID uint
//   - name string
func (_e *Repository_Expecter) FindByRoleIDAndName(roleID interface{}, name interface{}) *Repository_FindByRoleIDAndName_Call {
	return &Repository_FindByRoleIDAndName_Call{Call: _e.mock.On("FindByRoleIDAndName", roleID, name)}
}

func (_c *Repository_FindByRoleIDAndName_Call) Run(run func(roleID uint, name string)) *Repository_FindByRoleIDAndName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindByRoleIDAndName_Call) Return(_a0 *models.Permission, _a1 error) *Repository_FindByRoleIDAndName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByRoleIDAndName_Call) RunAndReturn(run func(uint, string) (*models.Permission, error)) *Repository_FindByRoleIDAndName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: permission
func (_m *Repository) Update(permission *models.Permission) error {
	ret := _m.Called(permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Permission) error); ok {
		r0 = rf(permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - permission *models.Permission
func (_e *Repository_Expecter) Update(permission interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", permission)}
}

func (_c *Repository_Update_Call) Run(run func(permission *models.Permission)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Permission))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(*models.Permission) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
